# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'AppDeck' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TwitterKit'
  pod 'TwitterCore'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBAudienceNetwork'
  pod 'ECSlidingViewController', :git => 'https://github.com/mdekermadec/ECSlidingViewController.git'
  #  pod 'ECSlidingViewController', '~> 2.0.3'
  pod 'SVProgressHUD'
  #  pod 'ARSPopover'
  pod 'SIAlertView'
  
  pod 'SSSnackbar'
  
  # begin appdeck-ios-plugins
  
  #pod 'appdeck-ios-iap', :git => 'https://github.com/Mobideck/appdeck-ios-iap.git'
  
  pod 'appdeck-ios-iap', :path => '~/Documents/git/plugins/appdeck-ios-iap'
  
  # end appdeck-ios-plugins
  
end

