# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'AppDeck' do
    
    use_frameworks!
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit', '~> 1.15.3'
    pod 'TwitterCore', '~> 1.15.3'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'FBAudienceNetwork' , '~> 4.27.2'
    pod 'Google-Mobile-Ads-SDK'
    pod 'ECSlidingViewController', :git => 'https://github.com/mdekermadec/ECSlidingViewController.git'
  #  pod 'ECSlidingViewController', '~> 2.0.3'
    pod 'SVProgressHUD', '~> 2.2.2'
  #  pod 'ARSPopover'
    pod 'SIAlertView'
    pod 'MaterialComponents/Snackbar', '~> 44.6.0'
    pod 'KAProgressLabel'
    pod 'Masonry'
    pod 'iCarousel', '~> 1.8'
    pod 'MapViewPlus'
  # pod 'KCFloatingActionButton', '~> 2.2'
    
  
  # pod 'SSSnackbar'
  
  # begin appdeck-ios-plugins
  
  #pod 'appdeck-ios-iap', :git => 'https://github.com/Mobideck/appdeck-ios-iap.git'
  
  #pod 'appdeck-ios-iap', :path => '~/Documents/git/plugins/appdeck-ios-iap'
  
  # end appdeck-ios-plugins
  
end



