# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'AppDeck' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TwitterKit'
  pod 'TwitterCore'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBAudienceNetwork'
  pod 'ECSlidingViewController', '~> 2.0.3'  
end

